// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDh5ruLSRLbsWaqkIAJ_LlcZnutuQqQhBY',
    appId: '1:885271584059:web:ee1c462039a6fb35b6ab1e',
    messagingSenderId: '885271584059',
    projectId: 'chemistry-coaching-app',
    authDomain: 'chemistry-coaching-app.firebaseapp.com',
    storageBucket: 'chemistry-coaching-app.firebasestorage.app',
    measurementId: 'G-NR9RLP9HQ1',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDwk8Mb7EvwEb0JKG08v59O-8B0S_XL2vw',
    appId: '1:885271584059:android:15105ce9a787b1c9b6ab1e',
    messagingSenderId: '885271584059',
    projectId: 'chemistry-coaching-app',
    storageBucket: 'chemistry-coaching-app.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCa_Oigf7yS9j7lB2XK0iUtuSDX8oEEfhE',
    appId: '1:885271584059:ios:e265a284c4043be5b6ab1e',
    messagingSenderId: '885271584059',
    projectId: 'chemistry-coaching-app',
    storageBucket: 'chemistry-coaching-app.firebasestorage.app',
    iosBundleId: 'com.example.chemistryCoachingApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCa_Oigf7yS9j7lB2XK0iUtuSDX8oEEfhE',
    appId: '1:885271584059:ios:e265a284c4043be5b6ab1e',
    messagingSenderId: '885271584059',
    projectId: 'chemistry-coaching-app',
    storageBucket: 'chemistry-coaching-app.firebasestorage.app',
    iosBundleId: 'com.example.chemistryCoachingApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDh5ruLSRLbsWaqkIAJ_LlcZnutuQqQhBY',
    appId: '1:885271584059:web:909d83aae44a3a45b6ab1e',
    messagingSenderId: '885271584059',
    projectId: 'chemistry-coaching-app',
    authDomain: 'chemistry-coaching-app.firebaseapp.com',
    storageBucket: 'chemistry-coaching-app.firebasestorage.app',
    measurementId: 'G-8EKLC2H2SF',
  );
}
